### ISSUE TITLE
The rootfs.tar path location for the registry job, needs to be configurable

### ISSUE THREAD

**Issue by qu1queee** [andrew-edgar/cube-release#9]

**Comment by loewenstein** [comment]
Actually for using BPM we will need tight control over where it is lying. We can easily mount anything under `/var/vcap/data`, but not `/var/vcap/packages` or `/var/vcap/jobs`. 
I have a [change](https://github.com/loewenstein/cube-release/blob/bpm/jobs/cube_registry/templates/pre-start) prepared that copies the rootfs tarball into `/var/vcap/data/rootfs` via pre-start hook. 

I am not yet sure this is the right way of doing things though.

**Comment by loewenstein** [comment]
@qu1queee Out of curiosity, why would the path have to be configurable?

**Comment by qu1queee** [comment]
@loewenstein good question, and there is no strong reason behind, it was just an assumption that this location could change somehow, which seems to not be the case.
